import { Login, Product} from "./app/shared/models/records";

export const sample_login: Login[] = [
  {
    name:"Arun",
    mobile:1234567890,
    password:"Arun+123",
    star:1,
  }
]

export const product: Product[] = [
    {
      title: "Stocks",
      content: [
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "4",
          rate: "500",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "RIP Aide",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
      ],

      status: "loss",
      amount: "1,00,00",
      price: "12,000",
    },
    {
      title: "Mutual Funds",
      content: [
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "4",
          rate: "500",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "RIP Aide",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
      ],

      status: "gain",
      amount: "20,000",
      price: "1000",
    },
    {
      title: "Commodities",
      content: [
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "4",
          rate: "500",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "RIP Aide",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Ram Dom",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "Tar Tar",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
        {
          name: "B.O. Thai",
          amount: "100",
          status: "gain",
          overallStatus: "loss",
          totalAmount: "49,800",
          percent: "2",
          rate: "200",
        },
      ],

      status: "loss",
      amount: "5000",
      price: "3000",
    }
]
